### ISSUE TITLE
feat: 로그인 유무에 따라 시작화면이 달라집니다.

### ISSUE THREAD

**Issue by Park-kxng** [boostcampwm-2024/iOS06-molio#101]
## 1. 이슈 내용
로그인, 비로그인 상태에 따라 시작화면이 달라집니다.

## 2. TODO
- [x] 스플래쉬 화면 구현
- [x] 로그인, 비로그인 시 UserDefault에 로그인 상태 값 저장하기
- [x] 로그인 상태에 따라 시작화면이 달라집니다.
