### ISSUE TITLE
feat: 필터 설정에 기반하여 추천 노래 불러오기

### ISSUE THREAD

**Issue by kybeen** [boostcampwm-2024/iOS06-molio#129]
## 1. 이슈 내용
장르 필터 화면에서 설정한 내용에 기반하여 추천 노래를 불러오는 기능을 구현합니다.

## 2. TODO
- [x] 필터 수정 시 현재 플레이리스트에 새 필터 정보로 업데이트
- [x] 변경된 필터로 노래 새로 불러오기
- [x] 저장 버튼 누르면 알럿 + 뒤로가기
- [x] 필터화면 나갔을 때 내비게이션 바 공간 차지하는 문제 수정
