### ISSUE TITLE
feat: 사용자는 본인 사진을 수정할 수 있어야 한다.

### ISSUE THREAD

**Issue by alstn38** [boostcampwm-2024/iOS06-molio#187]
## 1. 이슈 내용
사용자는 본인 사진을 수정할 수 있어야 합니다.

## 2. TODO
- [x] 이미지 선택 구현
- [x] 이미지 선택에 따른 서버 통신 저장
- [x] 변경된 이미지 적용
