### ISSUE TITLE
refactor: SettingView, MyInfoView UIHostingController 래퍼 구현

### ISSUE THREAD

**Issue by alstn38** [boostcampwm-2024/iOS06-molio#217]
## 1. 이슈 내용
기존에 만들어졌던 SettingView, MyInfoView는 SwiftUI의 View로만 이루어졌습니다.
하지만, 화면 전환의 경우 UIHostingController를 통해서 UIKit기반으로 수행해야하기 때문에 래퍼를 만들려고합니다.

## 2. TODO
- [x] SettingView UIHostingController 래퍼 구현
- [x] MyInfoView UIHostingController 래퍼 구현
- [x] SettingView -> MyInfoView 클로저를 통한 화면 전환 구현
