### ISSUE TITLE
feat: 설정화면 기능 구현

### ISSUE THREAD

**Issue by alstn38** [boostcampwm-2024/iOS06-molio#219]
## 1. 이슈 내용
설정화면에 있는 기능을 추가하려고 합니다.
[탈퇴 기능을 제외한 기능을 넣으려고 합니다.]

## 2. TODO
- [x] 내 프로필 나타내기
- [x] 로그인, 게스트에 따른 화면분리
- [x] 앱 버전 표시하기
- [x] 약관 . 및개인정보 처리 동의 페이지 구현하기
- [x] 로그 아웃 구현하기
