### ISSUE TITLE
feat: MusicKit에서 받아온 음악 데이터를 카드 화면에 표시한다.

### ISSUE THREAD

**Issue by alstn38** [boostcampwm-2024/iOS06-molio#23]
## 1. 이슈 내용
isrc를 사용해서 MusicKit을 통해 음악 정보를 받아온 이후의 작업입니다.
해당 음악 정보를 카드에 표시하는 작업을 수행합니다.

## 2. TODO
- [x]  화면에 표시할 Entity 정의하기
- [x] fetch Music UseCase 정의하기
- [x] Music Repository 정의하기
- [x]  MusicKit에서 가져온 데이터를 활용해서 카드 정보 표시하기
    - [x]  노래 제목 표시
    - [x]  장르 표시
    - [x]  아티스트 표시
    - [x]  앨범 이미지 표시
    - [x] 배경 색상 표시
