### ISSUE TITLE
feat: 게스트 상태인 경우 검색화면 이용을 제한하고 로그인을 할 수 있어야 한다.

### ISSUE THREAD

**Issue by alstn38** [boostcampwm-2024/iOS06-molio#307]
## 1. 이슈 내용
검색바를 통해 나오는 화면은 팔로우, 팔로잉 화면입니다.
게스트로 앱을 사용하는 경우에는 팔로우, 팔로잉 기능을 이용할 수 없기때문에 로그인을 유도해야합니다.

## 2. TODO
- [x] 게스트 유저인지 확인
- [x] 게스트 유저인 경우 검색화면을 덮는 로그인 화면 생성
- [x] 로그인 버튼 클릭시 로그인 View로 이동
