### ISSUE TITLE
feat: Swipe Action에 대한 결과를 SwipeViewModel에 보내야 합니다.

### ISSUE THREAD

**Issue by windowcow** [boostcampwm-2024/iOS06-molio#32]
## 1. 이슈 내용
관련 이슈: #29 

MusicDeck은 UI에 표시된 카드 더미와 일치합니다.
- 카드를 오른쪽 스와이프하면 SwipeViewModel.currentCardSwipedRight() 메서드를 실행하도록 해야 합니다.
    > 현재 이 코드는 SwipeMusicViewController의 handlePanGesture에 위치합니다.

- SwipeViewModel.currentCardSwipedRight메서드 내부에서는 deck에서 해당 로직에 대한 처리를 진행하도록 메시지를 보내는 코드가 존재해야 합니다.

## 2. TODO
- [x] 뷰 모델에서 MusicDeck을 의존성 주입 받아서 사용하기
- [x] 카드를 오른쪽 스와이프하면 SwipeViewModel.currentCardSwipedRight() 메서드를 실행하도록 하기
- [x] 왼쪽도 마찬가지로 하기

## 3. 참고자료
#29
