### ISSUE TITLE
feat: 애플 로그인을 파이어베이스를 통해 받아온 값을 저장합니다.

### ISSUE THREAD

**Issue by alstn38** [boostcampwm-2024/iOS06-molio#66]
## 1. 이슈 내용
사용자의 정보를 저장하고 활용해야하기 때문에 파이어베이스를 통한 애플 로그인을 진행해야합니다.

## 2. TODO
- [x] 애플 로그인을 위한 apple developer 설정
- [x] 애플 로그인을 위한 파이어베이스 설정
- [x] 파이어베이스를 통한 애플 로그인
